language: php
dist: xenial

php:
  - 7.3

services:
  - mysql

cache:
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"

branches:
  only:
    - /^8\.([0-9]+|x)\-[0-9]+\.([0-9]+|x)$/

env:
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin:$HOME/.config/composer/vendor/bin"
    - DRUPAL_TRAVIS_TEST_CODING_STYLES=false
    - DRUPAL_TRAVIS_VERBOSE=true

before_install:
  - composer global require thunder/travis

script:
  - test-drupal-project
