web_push_api.settings:
  type: config_object
  label: 'Web Push API settings'
  mapping:
    publicKey:
      type: path
      label: 'Public key'
      description: 'The path to file with a public key.'
    privateKey:
      type: path
      label: 'Private key'
      description: 'The path to file with a private key.'
